"""删除图书的唯一

Revision ID: 41883a049353
Revises: c0869cb55995
Create Date: 2018-09-23 11:30:53.109409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41883a049353'
down_revision = 'c0869cb55995'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='book')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'book', ['name'], unique=True)
    # ### end Alembic commands ###
